### ISSUE TITLE
Question: Request a thread

### ISSUE THREAD

**Issue by webghostx** [redwebcreation/twitter-stream-api#5]
Hello,

is it possible to get a whole thread? I don't see any possibility of just catching the thread through the tweet replies alone. Unless there are no answers on the side. 
It seems to me that the API doesn't offer any functions.

Regards

**Comment by felixdorn** [comment]
Hey!

Thanks for your interest!

Can you please detail your question, what do you mean by "get a whole thread" and "catching the thread through the tweet replies alone".

If you want to stop the stream after a given period of time, this is not possible due to the underlying implementation that uses Guzzle. Even if we remove Guzzle, I'm pretty sure we can't do that in PHP in a reliable way on all operating systems.

**Comment by webghostx** [comment]
The thread function of Twitter. You create a tweet and press + below to immediately add further answers. These are then all on the same line. I would like to access these specifically

But it seems to me that the API doesn't support this at all.

**Comment by felixdorn** [comment]
The scope of this package is limited to the Twitter **Stream** API and therefore we don't support any of the Twitter API's other features.
